# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c18cd12b0cc9475bcda8886629943924869a0dfbf12d5bf42bfbeb875b6c6fb3967da32d1c29cfb203472b62e9bc20b96a88aa96586067fbf8a95a6947ac050

test:
  secret_key_base: a866fd106e640b616e5dba686d08a548b537a7bbc517183bc82c200ef0b07a925d6a90bf7f937f64747cf376bda1868e573cb17782ba14964516bc110e0dcbcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
